### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by ghost** [SealBarkler/atom-python-run-lines#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [atom-python-run-lines](https://github.com/SealBarkler/atom-python-run-lines) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At C:\Users\79778\.atom\packages\atom-python-run-lines\lib\atom-python-run-lines.js:58

TypeError: Cannot read property 'path' of null
    at Object.run (/packages/atom-python-run-lines/lib/atom-python-run-lines.js:58:56)
    at HTMLElement.atomPythonRunLinesRun (/packages/atom-python-run-lines/lib/atom-python-run-lines.js:25:47)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:347765)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:1:752272)
    at EventEmitter.t (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:1:760195)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
 29x -4:01.0 core:backspace (input.hidden-input)
     -2:47.5.0 editor:newline (input.hidden-input)
  3x -2:45.4.0 core:backspace (input.hidden-input)
     -2:41.5.0 grammar-selector:show (atom-text-editor.editor.is-focused)
 24x -2:32.2.0 core:backspace (input.hidden-input)
     -0:19.8.0 atom-python-run-lines:runLines (input.hidden-input)
  3x -0:18.9.0 atom-python-run-lines:run (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.7 
atom-python-run-lines 0.2.0 
autocomplete-python 1.16.0 
ide-python 1.5.0 
kite 0.180.0 
```

**Comment by DebbieMatt** [comment]
Tbm gostaria de saber como resolver
